version: '3.8'

networks:
  controllers-network:
    driver: bridge

services:
  # === UNIFI STACK ===
  unifi-db:
    image: mongo:4.4
    container_name: unifi-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=unifi
      - MONGO_INITDB_ROOT_PASSWORD=unifi_secure_pass_2024
      - MONGO_INITDB_DATABASE=unifi
    volumes:
      - ./data/unifi-db:/data/db
    networks:
      - controllers-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Adicionado limite de recursos para o banco de dados como boa prática
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_secure_pass_2024
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    depends_on:
      - unifi-db
    volumes:
      - ./data/unifi-config:/config
      - ./ssl/unifi:/config/cert:ro
    ports:
      - "127.0.0.1:8443:8443"
      - "8080:8080"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "1900:1900/udp"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"
      - "5514:5514/udp"
    networks:
      - controllers-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8443", "-k"]
      interval: 30s
      timeout: 10s
      retries: 3
    # ADICIONADO LIMITE DE RECURSOS CONFORME SOLICITADO
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '2.0G'

  # === OMADA STACK ===
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8888
      - PORTAL_HTTPS_PORT=8844
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - TZ=America/Sao_Paulo
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
    volumes:
      - ./data/omada-data:/opt/tplink/EAPController/data
      - ./data/omada-logs:/opt/tplink/EAPController/logs
      - ./data/omada-backups:/opt/tplink/EAPController/data/autobackup
      - ./ssl/omada:/opt/tplink/EAPController/cert:ro
    ports:
      - "127.0.0.1:8088:8088"
      - "127.0.0.1:8043:8043"
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:8844:8844"
      - "127.0.0.1:27001:27001"
      - "127.0.0.1:29810:29810/udp"
      - "127.0.0.1:29811:29811"
      - "127.0.0.1:29812:29812"
      - "127.0.0.1:29813:29813"
      - "127.0.0.1:29814:29814"
      - "127.0.0.1:29815:29815"
      - "127.0.0.1:29816:29816"
    networks:
      - controllers-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8043", "-k"]
      interval: 30s
      timeout: 10s
      retries: 3
    # ADICIONADO LIMITE DE RECURSOS CONFORME SOLICITADO
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '2.0G'

# As definições de volumes nomeados são mantidas, embora não estejam sendo usadas nos serviços
volumes:
  unifi-db-data:
  unifi-config-data:
  omada-data:
  omada-logs:
  omada-backups:
